# Generated by Django 4.1 on 2022-08-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapi', '0003_alter_users_useradress_alter_users_userinnername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='UserAdress',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='UserInnerName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='UserPhone',
            field=models.IntegerField(null=True),
        ),
    ]
