# Generated by Django 4.1 on 2022-08-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapi', '0004_alter_users_useradress_alter_users_userinnername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Staff',
            field=models.BooleanField(blank=b'I01\n', default=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='UserAdress',
            field=models.TextField(blank=b'I01\n', null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='UserInnerName',
            field=models.CharField(blank=b'I01\n', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='UserPhone',
            field=models.IntegerField(blank=b'I01\n', null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='u_Admin',
            field=models.BooleanField(blank=b'I01\n', default=0),
        ),
    ]
