# Generated by Django 4.1 on 2022-08-21 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runapi', '0005_alter_users_staff_alter_users_useradress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meals',
            old_name='MealCategory',
            new_name='mealcategory',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='MealCost',
            new_name='mealcost',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='MealDescription',
            new_name='mealdescription',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='MealImage',
            new_name='mealimage',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='MealName',
            new_name='mealname',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='MealPoints',
            new_name='mealpoints',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='MealPrice',
            new_name='mealprice',
        ),
    ]
