# Generated by Django 4.1 on 2022-08-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapi', '0006_rename_mealcategory_meals_mealcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='mealcost',
            field=models.IntegerField(blank=b'I01\n', null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='mealdescription',
            field=models.TextField(blank=b'I01\n', null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='mealimage',
            field=models.ImageField(blank=b'I01\n', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='meals',
            name='mealprice',
            field=models.IntegerField(blank=b'I01\n', null=True),
        ),
    ]
