# Generated by Django 4.1 on 2022-08-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapi', '0007_alter_meals_mealcost_alter_meals_mealdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='mealimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
